### ISSUE TITLE
Not possible to get clock time on M5 Stack

### ISSUE THREAD

**Issue by jttait** [jttait/LogiTracker#8]
Will need to record time when initialising a new device. Then M5 Stack will just send elapsed time in snapshot and Processing will be used to calculate clock time on receiving snapshot.

**Comment by robmap** [comment]
Changed JSON output to have element "ellapsedTime" : int seconds

**Comment by jttait** [comment]
JSON format updated in README.md and desktop app.

**Comment by jttait** [comment]
Agreed format for desktop app and M5 agreed and captured in README.md
